### ISSUE TITLE
Trying to compile today unser msys2

### ISSUE THREAD

**Issue by chrhlnd** [donaldsonjw/bigloo#2]
Getting
- Configuring custom GC...
  configure: error: libatomic_ops is required.  You can either install it on
                your system, or fetch and unpack a recent version into the
                source directory and link or rename it to libatomic_ops.
  configure gc fail, see configure.log file.

I seem to have it though

$ ls /usr/include/
alpm.h  alpm_list.h  arpa  atomic_ops  atomic_ops.h  atomic_ops_malloc.h  atomic_ops_stack.h  FlexLexer.h  gawkapi.h  magic.h

$ ls /usr/lib
awk  coreutils  gawk  gettext  git-core  gnupg  libalpm.a  libatomic_ops.a  libatomic_ops_gpl.a  libfl.a  libfl_pic.a  libmagic.dll.a  libtz.a  openssl  p11-kit  perl5  pkcs11  pkgconfig  python2.7  python3.4  ssh  tar  terminfo

Not sure what I need to do to convince it.

configure.log has
- Java specific configuration (mingw)...
- GC configuration (yes)...
  ./autoconf/runtest -v1 -- gcflags "--cflags= -mthreads -D_MINGW_VER"
  -> -DNO_DEBUGGING -Iinclude -Ilibatomic_ops-install/include -DATOMIC_UNCOLLECTABLE -DNO_EXECUTE_PERMISSION -DGC_DLL -DGC_BUILD -DGC_DLL -DNO_EXECUTE_PERMISSION -DALLINTERIOR_POINTERS -DATOMIC_UNCOLLECTABLE -D_REENTRANT

./autoconf/runtest -v1 -- maemo.arm "--cflags=-O3"
Unknown option "--cflags=-O3", ignored
  -> no

./autoconf/runtest -v1 -- gcconfigureopt "--gc-dir=/d/projects/scheme/bigloo4.2a/gc/gc-7.4.2"
  -> --host=x86_64-pc-mingw64 --build=x86_64-pc-mingw64

**Comment by donaldsonjw** [comment]
Did you bootstrap the build yourself or use an archive, such as the one found at http://sandjsite.net/jwd/files/bigloo4.2b.tar.gz. If you did not use the archive, I suggest you try that one and see if it corrects your problem.

**Comment by chrhlnd** [comment]
yeah I downloaded

curl -O 'https://sandjsite.net/jwd/files/bigloo4.2a.tar.gz'

I"ll try the above link.

**Comment by chrhlnd** [comment]
Well I got farther, now make just hangs forever trying to compile things.

```
/d/projects/scheme/bigloo4.2b/bin/bigloo   -q -afile .afile -fsharing -fno-reflection -cc gcc -lib-dir /d/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -unsafev -gno-error-localization -no-hello -Wall -O2 +rm -g         -c Cfa/cfa.scm -o Cfa/cfa.o
gcc  -O3 -mthreads -D_MINGW_VER -c  -I. -ID:/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -I. -I/d/progs/bigloo/lib/bigloo/4.2b  Cfa/cfa.c
0
/d/projects/scheme/bigloo4.2b/bin/bigloo   -q -afile .afile -fsharing -fno-reflection -cc gcc -lib-dir /d/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -unsafev -gno-error-localization -no-hello -Wall -O2 +rm -g         -c Cfa/funcall.scm -o Cfa/funcall.o
gcc  -O3 -mthreads -D_MINGW_VER -c  -I. -ID:/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -I. -I/d/progs/bigloo/lib/bigloo/4.2b  Cfa/funcall.c
0
/d/projects/scheme/bigloo4.2b/bin/bigloo   -q -afile .afile -fsharing -fno-reflection -cc gcc -lib-dir /d/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -unsafev -gno-error-localization -no-hello -Wall -O2 +rm -g         -c Cfa/procedure.scm -o Cfa/procedure.o
gcc  -O3 -mthreads -D_MINGW_VER -c  -I. -ID:/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -I. -I/d/progs/bigloo/lib/bigloo/4.2b  Cfa/procedure.c
0
/d/projects/scheme/bigloo4.2b/bin/bigloo   -q -afile .afile -fsharing -fno-reflection -cc gcc -lib-dir /d/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -unsafev -gno-error-localization -no-hello -Wall -O2 +rm -g         -c Cfa/struct.scm -o Cfa/struct.o
gcc  -O3 -mthreads -D_MINGW_VER -c  -I. -ID:/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -I. -I/d/progs/bigloo/lib/bigloo/4.2b  Cfa/struct.c
0
/d/projects/scheme/bigloo4.2b/bin/bigloo   -q -afile .afile -fsharing -fno-reflection -cc gcc -lib-dir /d/projects/scheme/bigloo4.2b/lib/bigloo/4.2b -unsafev -gno-error-localization -no-hello -Wall -O2 +rm -g         -c Cfa/type.scm -o Cfa/type.o
```

no cpu time on bigloo.

**Comment by donaldsonjw** [comment]
I have had issues using multiple mark threads in the garbage collector with some versions of the msys2 runtime resulting in that behavior. Can you try setting the environment variable GC_MARKERS to 1(i.e., export GC_MARKERS=1) and see if that solves your problem? If it does, I may change the default gc configuration to not use multiple marker threads.

Let me know how it goes. Few people besides myself have used the MingW64 port, so I would not be surprised to find some rough edges that need to be addressed.

**Comment by chrhlnd** [comment]
`export GC_MARKERS=1; ./configure --prefix=/d/progs/bigloo --disable-libuv --disable-wav`

Worked thanks.

FYI

https://github.com/donaldsonjw/bigloo/wiki/Building-Bigloo-Under-Mingw64

Has the link I started with still being referenced.

**Comment by chrhlnd** [comment]
In my continuing saga to get this going. Ok now its compiled and "installed". I've added its path(s) to the Path var.

```
/d/progs/bigloo/bin:/d/progs/bigloo/lib/bigloo/4.2b
```

Now when running the client server example:

cd /d/projects/scheme/bigloo4.2b/examples/ClientServer

I'm trying to run the server

```
bigloo ./server.scm

gives error

Cannot open heap file "bigloo.heap" -- (. /d/progs/bigloo/lib/bigloo/4.2b)
    1. restore-heap@heap_restore, D:\projects\scheme\bigloo4.2b\comptime/Heap/restore.scm:45
    2. compiler@engine_compiler, D:\projects\scheme\bigloo4.2b\comptime/Engine/compiler.scm:97
    3. engine@engine_engine, D:\projects\scheme\bigloo4.2b\comptime/Engine/engine.scm:35
    4. main@init_main, D:\projects\scheme\bigloo4.2b\comptime/Init/main.scm:38


```

The file appears to be there but I'm guessing the pathing issues with MSYS and Windows are having fun.

**Comment by donaldsonjw** [comment]
Although msys is used to compile bigloo on Windows, it is a true windows application and expects the path to be Windows compatible. If d:/progra/bigloo/lib/4.2b is where the bigloo libraries are installed, you should set the BIGLOOLIB environment variable to that path. I recommend using the foreward slashes because the do not require escaping and are happily excepted by Windows. I believe this should solve your problem, but let me know if it does not.
